
exclude: [README.md]

collections:
  features:
    output: true
    permalink: features/:title/index.html
  essays:
    output: true
    permalink: essays/:title/index.html
  blogs-zunguzungu:
    output: true
    permalink: blogs/zunguzungu/:title/index.html
  blogs-the-beheld:
    output: true
    permalink: blogs/the-beheld/:title/index.html
  blogs-marginal-utility:
    output: true
    permalink: blogs/marginal-utility/:title/index.html

defaults:
  - scope:
      path: ""
      type: "features"
    values:
      layout: post
  - scope:
      path: ""
      type: "essays"
    values:
      layout: post
  - scope:
      path: ""
      type: "blogs-zunguzungu"
    values:
      layout: post
      author: Aaron Brady
  - scope:
      path: ""
      type: "blogs-the-beheld"
    values:
      layout: post
      author: Autumn Whitefield-Madrano
  - scope:
      path: ""
      type: "blogs-marginal-utility"
    values:
      layout: post
      author: Rob Horning
